const db = require("./db");

const sampleComplaints = [
  // ZOMATO COMPLAINTS
  {
    id: "zom00001",
    company: "zomato",
    platform: "Twitter/X",
    username: "@rahul_mumbai",
    text: "Zomato delivered my food 2 hours late and it was completely cold. This is unacceptable! #ZomatoFail",
    category: "Delivery",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    likes: 245,
    shares: 67,
    replies: 34,
    city: "Mumbai"
  },
  {
    id: "zom00002",
    company: "zomato",
    platform: "Reddit",
    username: "@priya_foodlover",
    text: "Ordered biryani from Zomato, received veg pulao instead. Called customer support and they put me on hold for 45 minutes. Never ordering again.",
    category: "Food Quality",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    likes: 189,
    shares: 43,
    replies: 28,
    city: "Delhi"
  },
  {
    id: "zom00003",
    company: "zomato",
    platform: "Google Reviews",
    username: "@amit_sharma",
    text: "Zomato app keeps crashing every time I try to place an order. Lost my cart 3 times today. Fix your app!",
    category: "App/Tech",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    likes: 156,
    shares: 34,
    replies: 19,
    city: "Bengaluru"
  },
  {
    id: "zom00004",
    company: "zomato",
    platform: "Facebook",
    username: "@sneha_pune",
    text: "Zomato charged me for an order that was never delivered. Raised complaint 5 days ago, still no refund. This is cheating!",
    category: "Refund",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    likes: 312,
    shares: 89,
    replies: 56,
    city: "Pune"
  },
  {
    id: "zom00005",
    company: "zomato",
    platform: "Twitter/X",
    username: "@vikram_chennai",
    text: "Zomato delivery partner was extremely rude and demanded extra tip. When I complained, customer care sided with the delivery boy. Pathetic!",
    category: "Customer Support",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 423,
    shares: 112,
    replies: 67,
    city: "Chennai"
  },
  {
    id: "zom00006",
    company: "zomato",
    platform: "Quora",
    username: "@meera_jaipur",
    text: "Food from Zomato arrived with broken packaging and items spilled everywhere. The food was clearly not handled with care during delivery.",
    category: "Hygiene",
    sentiment: "disappointed",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    likes: 178,
    shares: 45,
    replies: 23,
    city: "Jaipur"
  },
  {
    id: "zom00007",
    company: "zomato",
    platform: "Twitter/X",
    username: "@suresh_kolkata",
    text: "Zomato gold membership is a complete scam. Promised free deliveries but charged me every single time. Want my money back!",
    category: "Payment",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    likes: 534,
    shares: 145,
    replies: 89,
    city: "Kolkata"
  },
  {
    id: "zom00008",
    company: "zomato",
    platform: "Reddit",
    username: "@ananya_hyderabad",
    text: "My order shows delivered on Zomato app but nothing arrived at my door. This has happened 3 times this month alone!",
    category: "Delivery",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    likes: 267,
    shares: 78,
    replies: 45,
    city: "Hyderabad"
  },
  {
    id: "zom00009",
    company: "zomato",
    platform: "Google Reviews",
    username: "@rohit_ahmedabad",
    text: "Zomato cancelled my order after 1 hour of waiting without any explanation. Ruined my family dinner plans completely.",
    category: "Customer Support",
    sentiment: "disappointed",
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    likes: 198,
    shares: 56,
    replies: 34,
    city: "Ahmedabad"
  },
  {
    id: "zom00010",
    company: "zomato",
    platform: "Facebook",
    username: "@kavya_bhopal",
    text: "Found a cockroach in my food delivered by Zomato. This is a serious hygiene issue and I will be filing a formal complaint with food safety authorities.",
    category: "Hygiene",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    likes: 892,
    shares: 345,
    replies: 178,
    city: "Bhopal"
  },

  // SWIGGY COMPLAINTS
  {
    id: "swi00001",
    company: "swiggy",
    platform: "Twitter/X",
    username: "@vijay_delhi",
    text: "Swiggy charged me twice for the same order. Been waiting for refund for 2 weeks now. No response from support. Complete scam!",
    category: "Payment",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    likes: 423,
    shares: 112,
    replies: 67,
    city: "Delhi"
  },
  {
    id: "swi00002",
    company: "swiggy",
    platform: "Reddit",
    username: "@deepa_mumbai",
    text: "Swiggy delivery boy ate half my burger before delivering. The packaging was clearly opened and resealed. Disgusting behavior!",
    category: "Hygiene",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    likes: 567,
    shares: 189,
    replies: 123,
    city: "Mumbai"
  },
  {
    id: "swi00003",
    company: "swiggy",
    platform: "Google Reviews",
    username: "@kiran_bengaluru",
    text: "Swiggy One membership not working. Paying premium but not getting benefits. Customer care says wait 24 hours every single time I call.",
    category: "Customer Support",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    likes: 234,
    shares: 67,
    replies: 45,
    city: "Bengaluru"
  },
  {
    id: "swi00004",
    company: "swiggy",
    platform: "Facebook",
    username: "@rajesh_chennai",
    text: "Swiggy app showed estimated delivery 30 minutes. Order arrived after 2.5 hours. Food was stone cold and inedible. Total waste of money.",
    category: "Delivery",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    likes: 345,
    shares: 98,
    replies: 56,
    city: "Chennai"
  },
  {
    id: "swi00005",
    company: "swiggy",
    platform: "Twitter/X",
    username: "@pooja_pune",
    text: "Swiggy Instamart delivered expired products. Checked the date after eating and felt sick. This is dangerous and illegal!",
    category: "Food Quality",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 5.5 * 60 * 60 * 1000).toISOString(),
    likes: 678,
    shares: 234,
    replies: 145,
    city: "Pune"
  },
  {
    id: "swi00006",
    company: "swiggy",
    platform: "Quora",
    username: "@arjun_hyderabad",
    text: "Swiggy keeps cancelling my orders automatically and blaming restaurants. But when I call restaurants directly they say Swiggy never confirmed the order.",
    category: "App/Tech",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 6.5 * 60 * 60 * 1000).toISOString(),
    likes: 289,
    shares: 78,
    replies: 56,
    city: "Hyderabad"
  },
  {
    id: "swi00007",
    company: "swiggy",
    platform: "Reddit",
    username: "@nisha_kolkata",
    text: "Swiggy delivery partner was drunk and could barely speak. Very concerning behavior. Complained to Swiggy but got a bot response.",
    category: "Driver",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 7.5 * 60 * 60 * 1000).toISOString(),
    likes: 456,
    shares: 145,
    replies: 89,
    city: "Kolkata"
  },
  {
    id: "swi00008",
    company: "swiggy",
    platform: "Google Reviews",
    username: "@ganesh_jaipur",
    text: "Swiggy showing restaurant open but when order placed after 40 minutes told restaurant is closed. Why show false information?",
    category: "App/Tech",
    sentiment: "disappointed",
    timestamp: new Date(Date.now() - 8.5 * 60 * 60 * 1000).toISOString(),
    likes: 167,
    shares: 45,
    replies: 28,
    city: "Jaipur"
  },
  {
    id: "swi00009",
    company: "swiggy",
    platform: "Facebook",
    username: "@lakshmi_bhopal",
    text: "Ordered for 4 people from Swiggy. Only 2 items delivered out of 8. Refund given only for missing items not for ruined dinner party.",
    category: "Refund",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 9.5 * 60 * 60 * 1000).toISOString(),
    likes: 234,
    shares: 67,
    replies: 39,
    city: "Bhopal"
  },
  {
    id: "swi00010",
    company: "swiggy",
    platform: "Twitter/X",
    username: "@manoj_ahmedabad",
    text: "Swiggy support is completely useless. Chatbot gives same copy paste reply. No human agent available. Worst customer service in India.",
    category: "Customer Support",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 10.5 * 60 * 60 * 1000).toISOString(),
    likes: 512,
    shares: 167,
    replies: 98,
    city: "Ahmedabad"
  },

  // OLA COMPLAINTS
  {
    id: "ola00001",
    company: "ola",
    platform: "Twitter/X",
    username: "@sanjay_mumbai",
    text: "Ola driver cancelled my ride 4 times in a row during heavy rain. Left me stranded at midnight. This is completely irresponsible!",
    category: "Driver",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    likes: 678,
    shares: 234,
    replies: 145,
    city: "Mumbai"
  },
  {
    id: "ola00002",
    company: "ola",
    platform: "Reddit",
    username: "@divya_delhi",
    text: "Ola charged surge pricing of 4x during normal hours. App showed normal price then changed at payment. Feeling cheated and robbed.",
    category: "Payment",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    likes: 445,
    shares: 134,
    replies: 89,
    city: "Delhi"
  },
  {
    id: "ola00003",
    company: "ola",
    platform: "Google Reviews",
    username: "@suresh_bengaluru",
    text: "Ola auto driver took completely wrong route and demanded full fare. GPS showed longer route was deliberately chosen. This is fraud!",
    category: "Driver",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    likes: 356,
    shares: 112,
    replies: 78,
    city: "Bengaluru"
  },
  {
    id: "ola00004",
    company: "ola",
    platform: "Facebook",
    username: "@rekha_hyderabad",
    text: "Ola Electric scooter broke down in the middle of highway. No roadside assistance for 3 hours. Battery showed 40 percent when it died.",
    category: "App/Tech",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 789,
    shares: 267,
    replies: 167,
    city: "Hyderabad"
  },
  {
    id: "ola00005",
    company: "ola",
    platform: "Twitter/X",
    username: "@arun_chennai",
    text: "Ola driver was talking on phone the entire trip. Drove rashly and almost caused accident. Complained but got no response from Ola.",
    category: "Driver",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    likes: 523,
    shares: 178,
    replies: 112,
    city: "Chennai"
  },
  {
    id: "ola00006",
    company: "ola",
    platform: "Quora",
    username: "@preeti_pune",
    text: "Ola app shows driver arriving in 2 minutes for past 30 minutes. Driver location not moving on map. Classic Ola GPS fraud!",
    category: "App/Tech",
    sentiment: "frustrated",
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    likes: 345,
    shares: 98,
    replies: 67,
    city: "Pune"
  },
  {
    id: "ola00007",
    company: "ola",
    platform: "Reddit",
    username: "@kartik_kolkata",
    text: "Booked Ola Prime but got Mini. Driver refused to cancel so I would have to pay cancellation fee. This bait and switch must stop.",
    category: "Customer Support",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    likes: 412,
    shares: 134,
    replies: 89,
    city: "Kolkata"
  },
  {
    id: "ola00008",
    company: "ola",
    platform: "Google Reviews",
    username: "@sunita_jaipur",
    text: "Ola wallet money disappeared overnight. Had 500 rupees in wallet, now showing zero. Support saying no transaction history found.",
    category: "Payment",
    sentiment: "urgent",
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    likes: 567,
    shares: 189,
    replies: 123,
    city: "Jaipur"
  },
  {
    id: "ola00009",
    company: "ola",
    platform: "Facebook",
    username: "@mohan_bhopal",
    text: "Ola driver misbehaved with my wife and used abusive language. Filed complaint with police and Ola but company took no action against driver.",
    category: "Driver",
    sentiment: "angry",
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    likes: 934,
    shares: 456,
    replies: 234,
    city: "Bhopal"
  },
  {
    id: "ola00010",
    company: "ola",
    platform: "Twitter/X",
    username: "@ravi_ahmedabad",
    text: "Ola Electric S1 Pro battery degraded to 60 percent capacity in just 8 months. Service center says this is normal. Paid 1.3 lakhs for this!",
    category: "App/Tech",
    sentiment: "disappointed",
    timestamp: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    likes: 678,
    shares: 234,
    replies: 145,
    city: "Ahmedabad"
  },
];

const insert = db.prepare(`
  INSERT OR IGNORE INTO complaints
  (id, company, platform, username, text, category,
  sentiment, timestamp, likes, shares, replies, city)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

let count = 0;
sampleComplaints.forEach(c => {
  insert.run(
    c.id, c.company, c.platform, c.username,
    c.text, c.category, c.sentiment, c.timestamp,
    c.likes, c.shares, c.replies, c.city
  );
  count++;
});

console.log(`✅ Successfully added ${count} sample complaints to database!`);
console.log(`   🍕 Zomato: 10 complaints`);
console.log(`   🛵 Swiggy: 10 complaints`);
console.log(`   🚕 Ola:    10 complaints`);